# Generated by Django 4.1.4 on 2023-01-01 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_emp_delete_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Emp',
        ),
    ]
